In [2]:
!pip install numpy
import numpy as np

a=np.array([1,2,3,45])

print(a)
print(a.shape)
print(a.ndim)

[ 1  2  3 45]
(4,)
1


In [5]:
b=np.array([[1,2,3],[3,1,3,]])
print(b.shape)
print(b.ndim)

(2, 3)
2


In [6]:
print(a)
print(b)
print(a.dtype)
print(b.dtype)

[ 1  2  3 45]
[[1 2 3]
 [3 1 3]]
int32
int32


In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
c=np.arange(1,11)
d=np.arange(1,11,2)
print(c)
print(d)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [12]:
f=np.eye(6,dtype=int)
print(f)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [16]:
g=np.ones((2,3))
print(g)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
h=np.full((4,3),2,dtype=int)
h

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [18]:
print(np.diag(a))

[[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  3  0]
 [ 0  0  0 45]]


In [21]:
i=np.arange(1,17)
print(i)
print(i.shape)
print(i.ndim)
j=i.reshape(8,2)
print(j)
print(j.shape)
print(j.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
(16,)
1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]
(8, 2)
2


In [22]:
k=j.ravel()
print(a.ndim)

1


In [31]:
m=[1,2,3,4]
n=[1,2,3,4]
print(id(m))
print(id(n))
print(np.share_memory(m,n))
print(id(m))
print(id(n))

1855206785472
1855206743104
1855206785472
1855206743104


In [32]:
print(a.transpose())


[ 1  2  3 45]


In [38]:
u=np.array([1,2,3])
v=np.array([4,5,6])
np.hstack((u,v))
np.vstack((u,v))

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
print(np.insert(u,2,v))

[1 2 4 5 6 3]


In [41]:
np.delete(v,2)

array([4, 5])

In [45]:
np.sum(a)
np.sum(b,axis=1)
np.sum(f,axis=0)

array([1, 1, 1, 1, 1, 1])

In [46]:
np.exp(v)

array([ 54.59815003, 148.4131591 , 403.42879349])

In [51]:
np.mean(a)


12.75

In [52]:
np.median(v)

5.0

In [58]:
z=np.array([1,23,1,3,1])
z

array([ 1, 23,  1,  3,  1])

In [60]:
np.min(z)
np.max(z)

23

In [61]:
np.where(z==1)

(array([0, 2, 4], dtype=int64),)

In [70]:
np.median(v)

5.0

In [74]:
x=np.array([1,2,3,4,5,6,7,8,9])
np.where(x>4,x,0)

array([0, 0, 0, 0, 5, 6, 7, 8, 9])

In [75]:
x=np.array([1,2,3,4,5,6,7,8,9])
np.where(x<4,x,0)

array([1, 2, 3, 0, 0, 0, 0, 0, 0])

In [76]:
print(dir(list))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [77]:
print(dir(set))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']
